name: Get Teams Workflow
on: [ push, workflow_dispatch ]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Team Members
        run: |

          echo "Getting team members"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          echo "$TOEKN"
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/tdk.org/teams/tdkorgadmin/members
